name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checks out your repository to the workflow

    - name: Set up Python
      uses: actions/setup-python@v4  # Sets up Python 3.x
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Build MkDocs site
      run: mkdocs build  # Builds the static files for the site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # Deploys the site to the gh-pages branch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Uses GitHub's automatic token to push
        publish_dir: ./site  # The directory where MkDocs builds the static site
